### ISSUE TITLE
Request for the software and install instructions.

### ISSUE THREAD

**Issue by evannadeau** [UnexplodedMinds/Rosco2Garmin#1]
Hi, I would really like to use this to use my Stratux with Garmin Pilot.  Would I need to use an android device to be an in-between device?  Would my phone work for this task?

Thanks.

**Comment by Owenrichie** [comment]
I would like to use my Stratux to display Ads-b Traffic to my Garmin Pilot

**Comment by evannadeau** [comment]
Owenrichie, I have not heard back from this guy at all about using his method to use Stratux with Garmin Pilot. I did however find a side branch of Stratux and did get it working with GP, although you have to use GP in simulator mode. I don't believe weather works, but traffic, GPS and AHRS does work.  If interested, I can try sending you my image.

**Comment by Bartplackle** [comment]
> Owenrichie, I have not heard back from this guy at all about using his method to use Stratux with Garmin Pilot. I did however find a side branch of Stratux and did get it working with GP, although you have to use GP in simulator mode. I don't believe weather works, but traffic, GPS and AHRS does work. If interested, I can try sending you my image.

I would be very interested in this as well , Best regards Bart

**Comment by logix727** [comment]
> Owenrichie, I have not heard back from this guy at all about using his method to use Stratux with Garmin Pilot. I did however find a side branch of Stratux and did get it working with GP, although you have to use GP in simulator mode. I don't believe weather works, but traffic, GPS and AHRS does work. If interested, I can try sending you my image.

what fork is that and how to install @evannadeau

**Comment by evannadeau** [comment]
@logix727 and @Bartplackle you should not need this anymore.  Garmin Pilot has supported Stratux for over a year as of version 10.7 I believe.

https://generalaviationnews.com/2022/05/11/garmin-pilot-updated/

**Comment by logix727** [comment]
Not on Android .

**Comment by evannadeau** [comment]
Ah, gotcha.  Sorry for the issue.  I scoured my files and could not find the source repo I started from.  I very barely ever cobbled together something that kinda worked.  Someone else had framed it up.

I do believe it was to make Stratux look like X-Plane, and then you put Garmin Pilot in Simulator mode.

Maybe that will help you get something.



Evan
________________________________

**Comment by logix727** [comment]
Yes that's the route I'm looking for thru xplane

**Comment by evannadeau** [comment]
Try chasing this.  It sounds familiar.

Garmin Pilot wifi protocol, x-plane : r/stratux (reddit.com)<https://www.reddit.com/r/stratux/comments/6r733b/garmin_pilot_wifi_protocol_xplane/>
[https://share.redd.it/preview/post/6r733b]<https://www.reddit.com/r/stratux/comments/6r733b/garmin_pilot_wifi_protocol_xplane/>
r/stratux on Reddit: Garmin Pilot wifi protocol, x-plane<https://www.reddit.com/r/stratux/comments/6r733b/garmin_pilot_wifi_protocol_xplane/>
Posted by u/bdanza - 6 votes and 9 comments
www.reddit.com




Evan
________________________________
